### ISSUE TITLE
Are line breaks in examples ok?

### ISSUE THREAD

**Issue by r12a** [w3c/html-ruby#18]
Various examples in the spec use line breaks to make it easier to read the markup. I remember that we had to remove those line breaks in the early days, since they would distort the rendered output when converted to spaces. I think there was some discussion about use of line breaks subsequently, but i can't remember where we stand at the moment.  Perhaps this is described in the HTML spec, but does it apply equally to all styles of markup that are possible with ruby (eg. ones that don't have an rb element)?

I don't think the spec mentions this, either,  should it?

**Comment by kidayasuo** [comment]
It was not clear to me what is the issue that was brought up here. If it is about text transform within the ruby element it should be no different from normal text I suppose?

**Comment by r12a** [comment]
@kidayasuo when HTML source code is parsed, line breaks may be converted to spaces in the rendered output.

For example, there is no space at the end of the first line below
```
<p>hello
there</p>
```
but it is rendered
> hello there

[This test](https://w3c.github.io/i18n-tests/exploratory/index.html?text=%3Cruby%3Ea%3Crt%3Eb%3C%2Frt%3E%3C%2Fruby%3E%0A%3Cruby%3E%0Aa%0A%3Crt%3Eb%3C%2Frt%3E%0A%3C%2Fruby%3E%0A&css=.test%20%7B%20%20%7D&fontSize=36&width=500&height=500&a=&i=) shows that Gecko, Blink, & WebKit engines add spaces when there are newlines between ruby elements, and Gecko adds a space to the rendered rt when ruby base 'a' is followed by a newline (but not Blink or WebKit).

<img width="74" alt="Screenshot 2024-06-26 at 07 19 47" src="https://github.com/w3c/html-ruby/assets/4839211/67845947-dcef-473f-852e-1b1cd975542f">

I tested the examples in the spec and found the following for Firefox, but not for Chrome or Safari).  I can't remember which is expected, since i seem to vaguely remember that some space handling was introduced at some point to manage Latin annotations.  I wasn't keen to work through all the logic – it may be easier to just change the examples...

- Example 2, second code snippet: A space appears after měi
- Example 3: A space appears after ㄋㄠˇ
- Example 10: misaligned ず, and i think zu
- Example 11: seems to be a space after San Francisco

hope that helps clarify

**Comment by frivoal** [comment]
* Examples 1, 4, 5, 6, 7, 8, 9, 12 have no line breaks, so they're in the clear regardless

* Inter element line breaks / white space don't have any particular semantics (See https://html.spec.whatwg.org/multipage/dom.html#inter-element-whitespace), and are fully handled for layout purposes by CSS (https://drafts.csswg.org/css-ruby-1/#anon-gen-discard-space, https://drafts.csswg.org/css-ruby-1/#anon-gen-interpret-space, https://drafts.csswg.org/css-ruby-1/#base-annotation-pairing).

  Based on this, I think the following examples are in the clear:
  * example 2 code bloc 1
  * example 13
 
* For the rest, it's more complicated. Some examples have white-space at the end of the last auto-closed rt or implicit ruby annotation within an annotation level. They should be discarded and do not impact the layout based on css-text's rules for processing spaces at the start/end of lines (see https://drafts.csswg.org/css-ruby-1/#interlinear-layout and https://drafts.csswg.org/css-text-3/#white-space-phase-2 step 3). The same examples also have line-breaks/spaces at the end of the last auto-closed rb element or at the start of the first implicit ruby base, which is even trickier, because CSS text has some flexibility about how these get handled.
  * example 2 code bloc 2
  * example 3
  * example 10
  * example 11

I am thinking that this is a bit of a can of worms, and more over a layout can of worms, so it maybe be preferable to rewrite those examples either not to have line breaks at all, or at least to make sure all line breaks and spaces are inter-element spaces, and not within individual bases or individual annotations.

Make it into a one liner:
* example 2 code bloc 2

Either make it into a one-liner, or close `<rb>`, `<rt>`, `<rtc>` tags (either all of them, or the last one on each line):
* example 3
* example 10
* example 11

**Comment by kidayasuo** [comment]
Thank you for the clarification. A new line after the base character "a" results in adding a space to the content of the rt element seems like a bug to me (regardless of if it comes from the spac or the implementation)……

**Comment by r12a** [comment]
> I am thinking that this is a bit of a can of worms, and more over a layout can of worms, so it maybe be preferable to rewrite those examples either not to have line breaks at all, or at least to make sure all line breaks and spaces are inter-element spaces, and not within individual bases or individual annotations.

Yes, that's what i was thinking, too.

**Comment by frivoal** [comment]
Addressed by https://github.com/w3c/html-ruby/commit/657377b52fa245e77f44197288a4e35970f3ff2e
